/* Generated by CCAN configurator and modded by hand for Armory */
#ifndef CCAN_CONFIG_H
#define CCAN_CONFIG_H
#ifndef _GNU_SOURCE
#define _GNU_SOURCE /* Always use GNU extensions. */
#endif
#if defined(__arm__)
#define CCAN_COMPILER "arm-linux-gnueabihf-gcc"
#elif defined(_MSC_VER)
#define CCAN_COMPILER "cl"
#else
#define CCAN_COMPILER "cc"
#endif

/* CAVEAT: ARM (RPi) flags may need to be tweaked. Investigate later. */
#if defined(__arm__)
#define CCAN_CFLAGS "-std=gnu99 -I . -I ccan"
#elif defined(_MSC_VER)
#define CCAN_CFLAGS "-nologo -Zi -W4 -wd4200 -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS"
#elif defined(__APPLE__) && defined(__MACH__)
#define CCAN_CFLAGS "-g3 -ggdb -Wall -Wstrict-prototypes -Wold-style-definition -Wundef -Wmissing-prototypes -Wmissing-declarations -Wpointer-arith -Wwrite-strings -DCCAN_STR_DEBUG=1 -I. -arch x86_64"
#elif defined(__linux__)
#define CCAN_CFLAGS "-g3 -ggdb -Wall -Wstrict-prototypes -Wold-style-definition -Wundef -Wmissing-prototypes -Wmissing-declarations -Wpointer-arith -Wwrite-strings -DCCAN_STR_DEBUG=1 -I."
#else
#define CCAN_CFLAGS "-g3 -ggdb -Wall -Wstrict-prototypes -Wold-style-definition -Wundef -Wmissing-prototypes -Wmissing-declarations -Wpointer-arith -Wwrite-strings -DCCAN_STR_DEBUG=1 -I."
#endif

#if defined(_MSC_VER)
#define CCAN_OUTPUT_EXE_CFLAG "-Fe:"
#else
#define CCAN_OUTPUT_EXE_CFLAG "-o"
#endif

#define HAVE_CCAN 1

/* Flags needed by Armory */
#if defined(_MSC_VER)
#define HAVE_ATTRIBUTE_COLD 0
#else
#define HAVE_ATTRIBUTE_COLD 1
#endif
#if defined(_MSC_VER)
#define HAVE_ATTRIBUTE_CONST 0
#else
#define HAVE_ATTRIBUTE_CONST 1
#endif
#if defined(_MSC_VER)
#define HAVE_ATTRIBUTE_NORETURN 0
#else
#define HAVE_ATTRIBUTE_NORETURN 1
#endif
#if defined(_MSC_VER)
#define HAVE_ATTRIBUTE_PRINTF 0
#else
#define HAVE_ATTRIBUTE_PRINTF 1
#endif
#if defined(_MSC_VER)
#define HAVE_ATTRIBUTE_PURE 0
#else
#define HAVE_ATTRIBUTE_PURE 1
#endif
#if defined(_MSC_VER)
#define HAVE_ATTRIBUTE_UNUSED 0
#else
#define HAVE_ATTRIBUTE_UNUSED 1
#endif
#if defined(_MSC_VER)
#define HAVE_ATTRIBUTE_USED 0
#else
#define HAVE_ATTRIBUTE_USED 1
#endif
#define HAVE_BIG_ENDIAN 0
#if defined(__linux__) || defined(__arm__)
#define HAVE_BSWAP_64 1
#else
#define HAVE_BSWAP_64 0
#endif
#if defined(_MSC_VER)
#define HAVE_BUILTIN_CONSTANT_P 0
#else
#define HAVE_BUILTIN_CONSTANT_P 1
#endif
#if defined(__linux__) || defined(__arm__)
#define HAVE_BYTESWAP_H 1
#else
#define HAVE_BYTESWAP_H 0
#endif
#if defined(_MSC_VER)
#define HAVE_CLOCK_GETTIME 0
#else
#define HAVE_CLOCK_GETTIME 1
#endif
#define HAVE_LITTLE_ENDIAN 1
#if defined(_MSC_VER)
#define HAVE_STRUCT_TIMESPEC 0
#else
#define HAVE_STRUCT_TIMESPEC 1
#endif
#define HAVE_UNALIGNED_ACCESS 1
#if defined(_MSC_VER)
#define HAVE_WARN_UNUSED_RESULT 0
#else
#define HAVE_WARN_UNUSED_RESULT 1
#endif

/* Flags not needed by Armory - Set aside in case they're needed later */
#if defined(__linux__) || defined(_MSC_VER)
#define HAVE_32BIT_OFF_T 1
#else
#define HAVE_32BIT_OFF_T 0
#endif
#if defined(_MSC_VER)
#define HAVE_ALIGNOF 0
#else
#define HAVE_ALIGNOF 1
#endif
#if defined(_MSC_VER)
#define HAVE_ASPRINTF 0
#else
#define HAVE_ASPRINTF 1
#endif
#if defined(_MSC_VER)
#define HAVE_ATTRIBUTE_MAY_ALIAS 0
#else
#define HAVE_ATTRIBUTE_MAY_ALIAS 1
#endif
#if defined(_MSC_VER)
#define HAVE_BACKTRACE 0
#else
#define HAVE_BACKTRACE 1
#endif
#if defined(_MSC_VER)
#define HAVE_BUILTIN_CHOOSE_EXPR 0
#else
#define HAVE_BUILTIN_CHOOSE_EXPR 1
#endif
#if defined(_MSC_VER)
#define HAVE_BUILTIN_CLZ 0
#else
#define HAVE_BUILTIN_CLZ 1
#endif
#if defined(_MSC_VER)
#define HAVE_BUILTIN_CLZL 0
#else
#define HAVE_BUILTIN_CLZL 1
#endif
#if defined(_MSC_VER)
#define HAVE_BUILTIN_CLZLL 0
#else
#define HAVE_BUILTIN_CLZLL 1
#endif
#if defined(_MSC_VER)
#define HAVE_BUILTIN_CTZ 0
#else
#define HAVE_BUILTIN_CTZ 1
#endif
#if defined(_MSC_VER)
#define HAVE_BUILTIN_CTZL 0
#else
#define HAVE_BUILTIN_CTZL 1
#endif
#if defined(_MSC_VER)
#define HAVE_BUILTIN_CTZLL 0
#else
#define HAVE_BUILTIN_CTZLL 1
#endif
#if defined(_MSC_VER)
#define HAVE_BUILTIN_EXPECT 0
#else
#define HAVE_BUILTIN_EXPECT 1
#endif
#if defined(_MSC_VER)
#define HAVE_BUILTIN_FFS 0
#else
#define HAVE_BUILTIN_FFS 1
#endif
#if defined(_MSC_VER)
#define HAVE_BUILTIN_FFSL 0
#else
#define HAVE_BUILTIN_FFSL 1
#endif
#if defined(_MSC_VER)
#define HAVE_BUILTIN_FFSLL 0
#else
#define HAVE_BUILTIN_FFSLL 1
#endif
#if defined(_MSC_VER) || defined(__arm__)
#define HAVE_BUILTIN_POPCOUNT 0
#else
#define HAVE_BUILTIN_POPCOUNT 1
#endif
#if defined(_MSC_VER)
#define HAVE_BUILTIN_POPCOUNTL 0
#else
#define HAVE_BUILTIN_POPCOUNTL 1
#endif
#if defined(_MSC_VER) || defined(__arm__)
#define HAVE_BUILTIN_POPCOUNTLL 0
#else
#define HAVE_BUILTIN_POPCOUNTLL 1
#endif
#if defined(_MSC_VER)
#define HAVE_BUILTIN_TYPES_COMPATIBLE_P 0
#else
#define HAVE_BUILTIN_TYPES_COMPATIBLE_P 1
#endif
#define HAVE_ICCARM_INTRINSICS 0
#define HAVE_CLOCK_GETTIME_IN_LIBRT 0
#define HAVE_COMPOUND_LITERALS 1
#if defined(_MSC_VER)
#define HAVE_FCHDIR 0
#else
#define HAVE_FCHDIR 1
#endif
#if defined(_MSC_VER)
#define HAVE_ERR_H 0
#else
#define HAVE_ERR_H 1
#endif
#if defined(__arm__)
#define HAVE_FILE_OFFSET_BITS 1
#else
#define HAVE_FILE_OFFSET_BITS 0
#endif
#define HAVE_FOR_LOOP_DECLARATION 1
#define HAVE_FLEXIBLE_ARRAY_MEMBER 1
#if defined(_MSC_VER)
#define HAVE_GETPAGESIZE 0
#else
#define HAVE_GETPAGESIZE 1
#endif
#define HAVE_ISBLANK 1
#if defined(_MSC_VER)
#define HAVE_MEMMEM 0
#else
#define HAVE_MEMMEM 1
#endif
#if defined(__linux__) || defined(__arm__)
#define HAVE_MEMRCHR 1
#else
#define HAVE_MEMRCHR 0
#endif
#if defined(_MSC_VER)
#define HAVE_MMAP 0
#else
#define HAVE_MMAP 1
#endif
#if defined(__linux__) || defined(__arm__)
#define HAVE_PROC_SELF_MAPS 1
#else
#define HAVE_PROC_SELF_MAPS 0
#endif
#if defined(__linux__) || defined(__arm__)
#define HAVE_QSORT_R_PRIVATE_LAST 1
#else
#define HAVE_QSORT_R_PRIVATE_LAST 0
#endif
#if defined(__linux__) || defined(__arm__)
#define HAVE_SECTION_START_STOP 1
#else
#define HAVE_SECTION_START_STOP 0
#endif
#define HAVE_STACK_GROWS_UPWARDS 0
#if defined(_MSC_VER)
#define HAVE_STATEMENT_EXPR 0
#else
#define HAVE_STATEMENT_EXPR 1
#endif
#if defined(__APPLE__) && defined(__MACH__)
#define HAVE_SYS_FILIO_H 1
#else
#define HAVE_SYS_FILIO_H 0
#endif
#if defined(_MSC_VER)
#define HAVE_SYS_TERMIOS_H 0
#else
#define HAVE_SYS_TERMIOS_H 1
#endif
#if defined(_MSC_VER)
#define HAVE_SYS_UNISTD_H 0
#else
#define HAVE_SYS_UNISTD_H 1
#endif
#if defined(_MSC_VER)
#define HAVE_TYPEOF 0
#else
#define HAVE_TYPEOF 1
#endif
#if defined(_MSC_VER)
#define HAVE_UTIME 0
#else
#define HAVE_UTIME 1
#endif
#if defined(__linux__) || defined(__arm__)
#define HAVE_OPENMP 1
#else
#define HAVE_OPENMP 0
#endif
#if defined(_MSC_VER) || defined(__arm__)
#define HAVE_VALGRIND_MEMCHECK_H 0
#else
#define HAVE_VALGRIND_MEMCHECK_H 1
#endif
#if defined(__linux__) || defined(__arm__)
#define HAVE_UCONTEXT 1
#else
#define HAVE_UCONTEXT 0
#endif
#if defined(__linux__) || defined(__arm__)
#define HAVE_POINTER_SAFE_MAKECONTEXT 1
#else
#define HAVE_POINTER_SAFE_MAKECONTEXT 0
#endif
#endif /* CCAN_CONFIG_H */
